### ISSUE TITLE
Prototipo de alta

### ISSUE THREAD

**Issue by DenysRogeres** [fga-eps-mds/2023.1-Dnit-Back#6]
Prototipação de alta fidelidade da tela de recuperar senha

**Comment by DenysRogeres** [comment]
@ArturRSA19 Colocar link da documentacao

**Comment by ArturRSA19** [comment]
Link dos protótipos: https://www.figma.com/file/zyNXXEdSgbYnXQorSQPRgA/Prot%C3%B3tipos-de-Alta-Fidelidade---DNIT?type=design&node-id=0-1&t=bkHlWeEZ0082JGE6-0

Link da Documentação: https://fga-eps-mds.github.io/2023.1-Dnit-DOC/Prototipo/prototipo/
